image: python:3.10

pipelines:
  branches:
    main: # O cambia por master si tu rama principal se llama así
      - step:
          name: Sincronizar Proyecto de IA en GitHub
          script:
            - git remote add github git@github.com:CesarMauriciof/https://github.com/CesarMauriciof/proyecto-final
            - git push github main:main --force --tags
